- compile fix for msvc 14.24.28314
suyash/ulid pull request #7
Opened 2020-02-17 17:30 UTC by polymonster

MSVC\14.24.28314\include\random(1907,1): error C2338: note: char, signed char, unsigned char, char8_t, int8_t, and uint8_t are not allowed

Wonder if you are interested in supporting MSVC 14.24.28314 compiler.. not sure what other version of MSVC work or not, this is running on a GitHub action an I haven't tested it on windows myself yet!

Changing to uint32_t fixes the compiler error, I don't think this should cause any problems with the actual generated ulid? 

The uint128 implementation is just bit-wise or into a larger type anyway, so all the 0's in the upper 3 bytes won't make any difference, and this shouldn't affect performance either because it was already doing bitwise or of 2 different sized integer types.. in fact maybe you can improve performance by using the same sized integer (128) when doing the or?

the struct implementation is assigning 32bit values to 8bit array index, as we are in 0-255 should make no difference to result, maybe might affect performance, assigning the uint32 into a uint8?

2020-02-18 01:01 UTC, suyash commented
Initially I'm okay doing this under an `#ifdef _MSC_VER` or another VS specific macro.

> The uint128 implementation is just bit-wise or into a larger type anyway, so all the 0's in the upper 3 bytes won't make any difference, and this shouldn't affect performance either because it was already doing bitwise or of 2 different sized integer types.. in fact maybe you can improve performance by using the same sized integer (128) when doing the or?
>
> the struct implementation is assigning 32bit values to 8bit array index, as we are in 0-255 should make no difference to result, maybe might affect performance, assigning the uint32 into a uint8?

This has benchmarks. Can you post before and after numbers for both scenarios. `make bench` should do it. For linux and mac, travis should have run. Looking into it.

Also, if possible, can you also add the GitHub Workflow for windows.

Thanks

2020-03-16 14:24 UTC, suyash requested changes
Sorry for the late comment

2020-03-16 14:24 UTC, suyash commented on ulid_uint128.hh
> +#if #if _MSC_VER > 0
Typo, two `#if` statements.

Also, I don't think `__uint128_t` is available for visual studio, so maybe this file should be left unchanged?

2020-03-18 16:30 UTC, polymonster commented
> Sorry for the late comment

hey, I had a fix for that already (we are working in a perforce depot with a git mirror).. I have committed that now.

Sorry this is taking me a long time but haven't had time to add the MSVC GitHub Actions yet.. I will add them sometime soon when I get chance and then let you know.

I did try the benchmarks with different sized integers in the distribute function and couldn't really notice any performance difference..

Also thanks for this lib in the first place, we are using it for allocating unique ID's for a node graph editor and have been happy with it so far :)

2020-03-19 05:22 UTC, suyash approved these changes

2020-03-19 05:22 UTC, merged

2020-03-19 05:23 UTC, suyash commented
Thanks!